[workspace]
members = ["crates/*"]

# [dependencies]
# structopt = "0.3"
# ron = "0.8.0"
# once_cell = "1.16.0"
# simple_logger = "4.0"
# egui_glfw_gl = { git = "https://github.com/cohaereo/egui_glfw_gl", branch = "master" }
