use gl::types::*;

pub static mut OCTREE_NODE_POOL_TEXTURE: GLuint = 0;
pub static mut OCTREE_NODE_POOL_TEXTURE_BUFFER: GLuint = 0;

pub static mut OCTREE_NODE_POOL_BRICK_POINTERS_TEXTURE: GLuint = 0;
pub static mut OCTREE_NODE_POOL_BRICK_POINTERS_TEXTURE_BUFFER: GLuint = 0;

pub static mut OCTREE_NODE_POOL_NEIGHBOUR_X_TEXTURE: GLuint = 0;
pub static mut OCTREE_NODE_POOL_NEIGHBOUR_X_TEXTURE_BUFFER: GLuint = 0;

pub static mut OCTREE_NODE_POOL_NEIGHBOUR_X_NEGATIVE_TEXTURE: GLuint = 0;
pub static mut OCTREE_NODE_POOL_NEIGHBOUR_X_NEGATIVE_TEXTURE_BUFFER: GLuint = 0;

pub static mut OCTREE_NODE_POOL_NEIGHBOUR_Y_TEXTURE: GLuint = 0;
pub static mut OCTREE_NODE_POOL_NEIGHBOUR_Y_TEXTURE_BUFFER: GLuint = 0;

pub static mut OCTREE_NODE_POOL_NEIGHBOUR_Y_NEGATIVE_TEXTURE: GLuint = 0;
pub static mut OCTREE_NODE_POOL_NEIGHBOUR_Y_NEGATIVE_TEXTURE_BUFFER: GLuint = 0;

pub static mut OCTREE_NODE_POOL_NEIGHBOUR_Z_TEXTURE: GLuint = 0;
pub static mut OCTREE_NODE_POOL_NEIGHBOUR_Z_TEXTURE_BUFFER: GLuint = 0;

pub static mut OCTREE_NODE_POOL_NEIGHBOUR_Z_NEGATIVE_TEXTURE: GLuint = 0;
pub static mut OCTREE_NODE_POOL_NEIGHBOUR_Z_NEGATIVE_TEXTURE_BUFFER: GLuint = 0;

pub static mut TILES_PER_LEVEL: Vec<u32> = Vec::new();
